= Dark Patterns in Czechia: Finding them on the Czech Internet

== LOG ==

* *27.11. - Fifth meeting. - canceled by me* +
I was not able to find enough time to finish work from the forth meeting, because I was focusing on deadlines of tasks to MIE-MDW, NI-PYT, a semestral work to NI-MVI and my job as well. Because of that, I decided and Mr. Vitvar has aggreed, that we cancel our regular meetings before I finish the work to other classes and before I am able to show some results.

* *12.11. - Forth meeting. - canceled by me* +
Ran almost all the components in docker. Needs to connect them and run as a single image. I cancelled this meeting, because I had to work on other things to my work, where I had deadlines (chytrebydlim.cz). +

* *4.11. - Third meeting.* +
I could not show the working projectto Mr. Vitvar through, because it was laggy on the screen while I was streaming it onto MS Teams +
*Before the next meeting:* Try to run the project in Docker. Mr. Vitvar created an image on school server for the crawler, because a lot of data is going to be downloaded. Mr. Vitvar will send a selenium image run as a Docker image +

* *1.11. - Third meeting - moved to 4.11.* +
+I was successful to run their project in a virtual Ubuntu image. Mr. Vitvar could not visit the meeting, so we moved it to other day.+

* *16.10. - Second meeting.* +
I was not successful with running their project. Problem is, that they used old Python 2.7, which is not supported anymore and because of that, a lot of packages in requirements.txt are not available online anymore. Also spaCy wordlist should be installed directly throught spaCy framework and not thought pip. +
I found out that they used more programming languages (R, Java, Python and Javascript) than expected. They used Python and Javascript for crawling. Celery framework, OpenWPN are used to crawl hundreds of million pages. MutationObserver is used in webscraping and classification of changed UI elements over some period of time. (Some dark patterns changes their color, bg-color or other style after some certain actions.) +
*Before the next meeting:* Try once again to run https://github.com/aruneshmathur/dark-patterns[this implementation] to detect dark patterns on a Czech Website (Now easier than: Alza.cz, because Alza can block crawler). If crawling will not work, download HTML and try data extraction.

* *1.10. - First meeting.* +
Topic clarifications. I showed https://github.com/Lznah/DarkPatterns/blob/master/misc/mindmap.png[a mindmap], that I created. +
*Before the next meeting:* Try to run https://github.com/aruneshmathur/dark-patterns[this implementation] to detect dark patterns on a Czech Website (For example: Alza.cz)
